services:
  minecraft:
    container_name: Minecraft
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: ${TYPE}
      VERSION: ${VERSION}
      INIT_MEMORY: ${INIT_MEMORY}
      MAX_MEMORY: ${MAX_MEMORY}
      SERVER_NAME: ${SERVER_NAME}
      LEVEL_NAME: ${LEVEL_NAME}
      SERVER_PORT: "25565"
      DIFFICULTY: ${DIFFICULTY}
      GAMEMODE: ${GAMEMODE}
      MAX_PLAYERS: ${MAX_PLAYERS}
      ENABLE_WHITELIST: ${ENABLE_WHITELIST}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${SIMULATION_DISTANCE}
      ONLINE_MODE: ${ONLINE_MODE}
      ENABLE_RCON: ${ENABLE_RCON}
      RCON_PASSWORD: ${RCON_PASSWORD}
      MODRINTH_PROJECTS: ${MODRINTH_PROJECTS}
    tty: true
    ports:
      - "25565:25565"
      - "19132:19132/udp"
      - "25575:25575"
    restart: unless-stopped
    stdin_open: true
    working_dir: /
    volumes:
      - ./.data:/data
      - ./mods:/mods

  minecraft-restic:
    container_name: Minecraft-Backup
    build:
      context: ./restic
    environment:
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      RESTIC_CRON_SCHEDULE: "0 5 * * *"
      RESTIC_CRON_LOG_PATH: "/proc/1/fd/1"
      RESTIC_FORGET_ARGS: "--keep-daily 3 --keep-monthly 3 --prune"
      RESTIC_RUN_ON_STARTUP: "false"
      TZ: "Europe/Madrid"
    volumes:
      - ./.data:/data:ro
    restart: always
