version: '3'
services:
  minecraft:
    container_name: Minecraft
    image: itzg/minecraft-server
    environment:
     EULA: "TRUE"
     SERVER_NAME: ${SERVER_NAME}
     SERVER_PORT: "25565"
     DIFFICULTY: ${DIFFICULTY}
     GAMEMODE: ${GAMEMODE}
     LEVEL_NAME: ${LEVEL_NAME}
     MAX_PLAYERS: ${MAX_PLAYERS}
    tty: true
    ports:
      - "25565:25565"
    restart: unless-stopped
    stdin_open: true
    working_dir: /
    volumes: 
     - minecraftdata:/data
     - ./plugins:/plugins
volumes:
 minecraftdata:
  external: true
