services:
  minecraft:
    container_name: Minecraft
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: ${TYPE}
      VERSION: ${VERSION}
      MEMORY: ${MEMORY}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_PORT: "25565"
      DIFFICULTY: ${DIFFICULTY}
      GAMEMODE: ${GAMEMODE}
      MAX_PLAYERS: ${MAX_PLAYERS}
      ENABLE_WHITELIST: ${ENABLE_WHITELIST}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${SIMULATION_DISTANCE}
      ONLINE_MODE: ${ONLINE_MODE}
      MODRINTH_PROJECTS: ${MODRINTH_PROJECTS}
    tty: true
    ports:
      - "25565:25565"
    restart: unless-stopped
    stdin_open: true
    working_dir: /
    volumes:
      - ./data:/data
      - ./mods:/mods
  geyser:
    container_name: Geyser
    image: ghcr.io/geysermc/geyser:latest
    depends_on:
      - minecraft
    ports:
      - "19132:19132/udp"
    restart: unless-stopped
    volumes:
      - ./geyser:/config
